<?php $this->init() ?>
<div class="row">
  <?php $this->echoBrickA(); ?>
  <?php $this->echoBrickB(); ?>
  <?php $this->echoBrickC(); ?>
</div>


<!--
      <div class="row">
        <div class="col-xs-6 box-header nopadding">
          <img class="bg-box-header" src="assets/bg-1-box-header.png">
            <div class="content-box-header">
              <h4 class="content-box-title black-text">your high-speed<br /> equipment.</h4>
              <p class="content-box-subtitle black-text">Up to 22 Mbit with a small satellite <br /> dish and a modem.</p>

              <div class="clearfix"></div>
              <a href="#" class="puls-box-header puls-bgBlue">find out more</a>
            </div>
        </div>
        <div class="col-xs-3 box-header nopadding">
          <img class="bg-box-header" src="assets/bg-2-box-header.png">
            <div class="content-box-header">
              <h4 class="content-box-title">your high-speed<br /> equipment.</h4>
              <p class="content-box-subtitle">Up to 22 Mbit with a small satellite <br /> dish and a modem.</p>
              <div class="clearfix"></div>
              <a href="#" class="puls-box-header">find out more</a>
            </div>
        </div>

        <div class="col-xs-3 box-header nopadding">
          <img class="bg-box-header" src="assets/bg-3-box-header.png">
            <div class="content-box-header">
              <h4 class="content-box-title">your high-speed<br /> equipment.</h4>
              <p class="content-box-subtitle">Up to 22 Mbit with a small satellite <br /> dish and a modem.</p>
              <div class="col-xs-4">
                <img class="icon-box-header" src="assets/icon-22mb.png">
              </div>
              <div class="col-xs-4">
                <img class="icon-box-header" src="assets/icon-parabola.png">
              </div>
              <div class="col-xs-4">
                <img class="icon-box-header" src="assets/icon-modem.png">
              </div>
              <div class="clearfix"></div>
              <a href="#" class="puls-box-header">find out more</a>
            </div>
        </div>
      </div>-->